-- LUA INIT
require "config.goto"
require "config.diag"
require "config.icons"
--require "config.lsputils"
--require "config.lspnav"
require "config.symbols"
require "config.lspsaga"
require "config.telescope"
require "config.treesitter"
require "config.fold"
require "config.statusline"
require "config.autocmd"
require "config.formater"
require "config.startify"
require "config.bookmarks"
--require "config.neogit"
require "config.diffview"
