-- LUA INIT
require "config.symbols"
require "config.telescope"
require "config.treesitter"
require "config.fold"
require "config.statusline"
require "config.autocmd"
require "config.formater"
require "config.startify"
require "config.bookmarks"
require "config.diffview"
require "config.flutter"
